config/routes.rb
Rails.application.routes.draw do

  resources :asks do
    member do
      get 'show_detail'
      post 'like'
    end
  end

  resources :ask_tmps, only: [:create]

  resources :votes, only: [:create, :destroy]

  resources :comments, only: [:index, :create, :update, :destroy] do
    member do
      post 'like'
    end
  end

  resources :preview_images, only: [:show, :create, :update]

  resources :deals, only: [] do
    collection do
      get 'get_naver_deals'
      post 'create_by_naver'
    end
  end

  resources :collections, only: [:index, :show]

  resources :videos, only: [:index, :show]

  resources :search, only: [:index] do
    collection do
      get 'keyword'
    end
  end

  resources :user_gcm_keys, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/facebook', to: 'users/facebook#auth'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'users/check_email', to: 'users/registrations#check_email'

    get 'users/forgot_password', to: 'users/passwords#new'
    get 'users/reset_password', to: 'users/passwords#edit'

    get 'users/alarm_check', to: 'users/sessions#alarm_check'
    get 'users/get_user_profile', to: 'users/sessions#get_user_profile'
    get 'users/get_user_alarms', to: 'users/sessions#get_user_alarms'
    get 'users/get_my_recent_ask', to: 'users/sessions#get_my_recent_ask'

    get 'users/', to: 'users/sessions#users'
    get 'users/history', to: 'users/sessions#history'
    get 'users/settings', to: 'users/sessions#settings'

    get 'users/settings/edit_profile', to: 'users/sessions#edit_profile'
    delete 'users/destroy_user_picture', to: 'users/sessions#destroy_user_picture'
    put 'users/change_nickname', to: 'users/sessions#change_nickname'

    get 'users/settings/edit_password', to: 'users/sessions#edit_password'
    put 'users/change_password', to: 'users/sessions#update_password'

    get 'users/settings/edit_push_alarm', to: 'users/sessions#edit_push_alarm'
    get 'users/settings/edit_email_alarm', to: 'users/sessions#edit_email_alarm'
    put 'users/toggle_alarm_option', to: 'users/sessions#toggle_alarm_option'
  end

  resources :log_errors, only: [:create]
  resources :log_inquiries, only: [:create]
  resources :log_reports, only: [:create]

  resources :shares, only: [:new, :create]
  resources :share_logs, only: [:create]

  resources :alarms, only: [:index]

  resources :etc, only: [] do
    collection do
      get 'access_term'
      get 'privacy_policy'
      get 'contact_us'
      get 'faq_help'
    end
  end

  get 'landing', to: 'home#landing'
  get 'open_app', to: 'home#open_app'

  namespace :admin do
    get '/', to: 'home#index'
    post '/sign_in', to: 'home#create'
    delete '/sign_out', to: 'home#destroy'
    resources :asks, only: [:index, :show, :update]
    resources :events
    resources :collections
    resources :collection_keywords, only: [:index, :create]
    resources :collection_to_collection_keywords, only: [:index]
    resources :collection_to_asks, only: [:create]
    resources :videos
    resources :grade_standards do
      put :force_update, on: :collection
      patch :cancel_modify, on: :member
    end
    resource :search_keywords, only: [:show, :create, :update, :destroy]
    resources :refer_links, except: [:delete]
    resources :pushes, only: [:index, :new, :create] do
      get :target, on: :collection
      get :test, on: :collection
    end
    resources :mails, except: [:edit, :update, :destroy] do
      get :target, on: :collection
      get :template, on: :collection
      post :test, on: :collection
    end
    resources :tables, only: [:index] do
      get ':table_name', to: 'tables#index', on: :collection
    end
    resources :analysis, only: [:index]
  end

  get 'templates/faq_help', to: 'templates#faq_help'
  get 'templates/access_term', to: 'templates#access_term'
  get 'templates/privacy_policy', to: 'templates#privacy_policy'

  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :ask

  has_attached_file :image,
                    url: '/assets/events/:id/:style/:basename.:extension',
                    path: ':rails_root/public/assets/events/:id/:style/:basename.:extension',
                    default_url: '/images/custom/card_image_preview.png'
  validates_attachment_size :image, less_than: 20.megabytes
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/pjpeg', 'image/pjpeg', 'image/png', 'image/jpg', 'image/gif', 'application/octet-stream']

  validates :title, presence: true
  validates :description, presence: true
  validates :ask_id, presence: true
  validates :started_at, presence: true
  validates :ended_at, presence: true
  validates :image, presence: true

  before_post_process :rename_file

  def rename_file
    return if image.blank?
    extension = image_file_name.split('.').last
    return unless %w[jpg jpeg gif png].include?(extension)
    self.image_file_name = "event.#{extension}"
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::HomeController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /admin/events
  def index
    @schedules =
      Event.where('started_at >= ?', Time.now)
           .order(started_at: :asc)
    @ongoings =
      Event.where('started_at < ? AND ended_at > ?', Time.now, Time.now)
           .order(ended_at: :desc)
    @events =
      Event.where('ended_at <= ?', Time.now)
           .order(id: :desc)
           .page(params[:page]).per(10)
  end

  # GET /admin/events/:id
  def show
  end

  # GET /admin/events/new
  def new
    @event = Event.new
  end

  # POST /admin/events
  def create
    @event = Event.new(event_params)
    unless Time.new(event_params['ended_at(1i)'], event_params['ended_at(2i)'], event_params['ended_at(3i)']) > Time.new(event_params['started_at(1i)'], event_params['started_at(2i)'], event_params['started_at(3i)'])
      flash['error'] = '종료일자는 시작일자보다 이후여야만 합니다'
      render :new and return
    end
    if @event.save
      @event.ask.update(event_id: @event.id)
      flash['success'] = "<#{@event.title}> 이벤트를 성공적으로 생성하였습니다"
      redirect_to admin_events_path
    else
      flash['error'] = '필수 입력값을 모두 입력해주세요'
      render :new
    end
  end

  # GET /admin/events/:id/edit
  def edit
  end

  # PATCH /admin/events/:id
  def update
    unless Time.new(event_params['ended_at(1i)'], event_params['ended_at(2i)'], event_params['ended_at(3i)']) > Time.new(event_params['started_at(1i)'], event_params['started_at(2i)'], event_params['started_at(3i)'])
      flash['error'] = '종료일자는 시작일자보다 이후여야만 합니다'
      render :edit and return
    end
    if @event.update(event_params)
      flash['success'] = "<#{@event.title}> 이벤트를 성공적으로 수정하였습니다"
      redirect_to admin_events_path
    else
      flash['error'] = '필수 입력값을 모두 입력해주세요'
      render :edit
    end
  end

  # DELETE /admin/events/:id
  def destroy
    @event.destroy
    @event.ask.update(event_id: nil)
    flash['warning'] = "<#{@event.title}> 이벤트를 삭제하였습니다"
    redirect_to :back
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title,
                                  :description,
                                  :ask_id,
                                  :started_at,
                                  :ended_at,
                                  :label,
                                  :image)
  end
end

app/views/admin/events/_form.html.erb
<%= simple_form_for @event,
                    url: @event.id.nil? ? admin_events_path : admin_event_path(@event.id),
                    html: { id: 'event_form', oninput: 'form_check($(this));', onchange: 'form_check($(this));' } do |f| %>
  <% if @event.id.nil? %>
    <div class="jumbotron clearfix">
      <h1>이벤트 생성하기</h1>
      <p>새로운 이벤트를 생성합니다</p>
      <%= link_to '목록으로',
                  admin_events_path,
                  class: 'btn btn-default btn-lg' %>
      <%= f.button :submit,
                   '생성하기',
                   class: 'btn btn-lg btn-success pull-right',
                   disabled: true,
                   onclick: 'window.onbeforeunload = null;',
                   data: { confirm: '정말로 생성하시겠어요?', disable_with: '생성중...' } %>
    </div>
    <div class="panel panel-success">
      <!-- Default panel contents -->
      <div class="panel-heading">이벤트 생성</div>
  <% else %>
    <div class="jumbotron clearfix">
      <h1>이벤트 수정하기</h1>
      <p>이벤트의 내용을 수정합니다</p>
      <%= link_to '목록으로',
                  admin_events_path,
                  class: 'btn btn-default btn-lg' %>
      <%= f.button :submit,
                   '수정하기',
                   class: 'btn btn-warning btn-lg pull-right',
                   disabled: true,
                   onclick: 'window.onbeforeunload = null;',
                   data: { confirm: '정말로 수정하시겠어요?', disable_with: '수정중...' } %>
    </div>
    <div class="panel panel-warning">
      <!-- Default panel contents -->
      <div class="panel-heading"><kbd><%= @event.id %>번</kbd> 이벤트 수정</div>
  <% end %>
      <div class="panel-body">
        <div class="form-inputs">
          <%= f.input :title,
                      as: :string,
                      label: '1. 제목 입력',
                      error: '',
                      input_html: {
                                    class: 'required_form',
                                    placeholder: '이벤트 제목을 입력하세요'
                                  } %>
          <%= f.input :description,
                      as: :text,
                      label: '2. 설명 입력',
                      error: '',
                      input_html: {
                                    rows: 5,
                                    class: 'required_form',
                                    placeholder: '이벤트 설명을 입력하세요'
                                  } %>
          <%= f.input :label,
                      as: :select,
                      collection: [['이벤트 라벨을 강조하여 표시합니다', true], ['이벤트 라벨을 표시하지 않습니다', false]],
                      prompt: false,
                      label: '3. 이벤트 라벨 표시 여부',
                      hint: '이벤트 라벨을 강조하여 표시할지 여부를 선택합니다',
                      error: '' %>
          <div class="row form-group">
            <%= f.input :started_at,
                        as: :date,
                        label: '4. 이벤트 시작일자 입력',
                        hint: '시작일자를 현재일자 이후로 등록하면 예약 이벤트 생성이 가능합니다',
                        error: '',
                        wrapper_html: { class: ' col-lg-6 col-md-6 col-sm-6 col-xs-12' },
                        input_html: { class: 'required_form' } %>
            <%= f.input :ended_at,
                        as: :date,
                        label: '5. 이벤트 종료일자 입력',
                        hint: '종료일자는 종료를 원하는 해당일자의 다음날을 입력하세요 (매일 자정 기준) 종료일자가 지나면 자동으로 상단 고정이 해제됩니다',
                        error: '',
                        wrapper_html: { class: ' col-lg-6 col-md-6 col-sm-6 col-xs-12' },
                        input_html: { class: 'required_form' } %>
          </div>
          <%= f.input :image,
                      label: '6. 썸네일 입력',
                      error: '' do %>
            <%= f.input_field :image,
                              as: :file,
                              class: 'hidden',
                              onclick: 'this.nextElementSibling.checked = true;',
                              onchange: 'preview_thumbnail(this);' %>
            <%= check_box_tag 'image_attached', '', @event.id.nil? ? false : true, class: 'hidden required_form' %>
            <p class="help-block">아래 이미지를 클릭하거나, 파일을 드래그&드롭하세요</p>
            <p class="help-block">권장해상도는 900*600 픽셀입니다</p>
            <p class="help-block">업로드 전 <a href="https://tinypng.com/" target="_blank">tinypng.com</a>에서 이미지 용량을 꼭 줄여주세요</p>
            <div class="well">
              <%= image_tag @event.image.url(:original),
                           { id: 'thumbnail_image',
                             class: 'img-thumbnail center-block',
                             style: 'cursor: pointer;',
                             onclick: '$("#event_image").click();',
                             onload: 'drag_n_drop_img(this);' } %>
            </div>
          <% end %>
          <%= f.input :ask_id,
                      label: '7. 질문 입력',
                      error: '' do %>
              <p class="help-block">질문 컨텐츠 ID를 입력한 뒤 미리보기 버튼을 누르세요</p>
              <div class="input-group">
              <%= f.input_field :ask_id,
                                as: :integer,
                                class: 'form-control',
                                placeholder: '질문 ID를 입력해주세요',
                                pattern: '[0-9]*',
                                min: '1',
                                onchange: "$('#ask_preview_link_btn').click();" %>
              <span class="input-group-btn">
                <button id="ask_preview_link_btn" class="btn btn-success" type="button" onclick="preview_link('ask_id', $('#event_ask_id'), null, $('#ask_link_preview'), $('#ask_preview_completed'));"><i class="fa fa-search"></i> 미리보기</button>
              </span>
            </div>
            <%= check_box_tag 'ask_preview_completed', '', @event.id.nil? ? false : true, class: 'hidden required_form' %>
          <% end %>
          <div id="ask_link_preview" class="well <%= 'hidden' if @event.ask_id.blank? %>">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="<%= "#{CONFIG["host"]}/asks/#{@event.ask_id}" unless @event.ask_id.blank? %>"></iframe>
              <div class="iframe_cover" onclick="window.open($(this).prev('iframe').attr('src'));"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

<script>
  $.each($('#event_started_at_1i option'), function( index, value ) { if (value.value !== '') value.text += '년'; });
  $.each($('#event_started_at_3i option'), function( index, value ) { if (value.value !== '') value.text += '일'; });
  $.each($('#event_ended_at_1i option'), function( index, value ) { if (value.value !== '') value.text += '년'; });
  $.each($('#event_ended_at_3i option'), function( index, value ) { if (value.value !== '') value.text += '일'; });
</script>

app/views/admin/events/index.html.erb
<div class="jumbotron clearfix">
  <h1>이벤트 목록</h1>
  <p>이벤트를 생성하거나 수정, 발행할 수 있습니다</p>
  <%= link_to '새로운 이벤트 생성하기',
              new_admin_event_path,
              { class: 'btn btn-success btn-lg pull-right' } %>
</div>


<% unless @schedules.blank? %>
  <div class="panel panel-warning">
    <!-- Default panel contents -->
    <div class="panel-heading">예정중인 이벤트 목록</div>

    <!-- Table -->
    <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th style="width: 5%;">순번</th>
            <th style="width: 7.5%;">라벨</th>
            <th style="width: 20%;">이미지</th>
            <th style="width: 15%;">제목</th>
            <th style="width: 10%;">시작일</th>
            <th style="width: 20%;">기간</th>
            <th style="width: 7.5%;">조회</th>
            <th style="width: 7.5%;">수정</th>
            <th style="width: 7.5%;">삭제</th>
          </tr>
        </thead>
        <tbody>
          <% @schedules.each_with_index do |event, index| %>
            <tr>
              <th><kbd><%= index + 1 %>번째</kbd></th>
              <td><%= event.label ? '<i class="fa fa-check text-success"></i>'.html_safe : '<i class="fa fa-remove text-danger"></i>'.html_safe %></td>
              <td><%= image_tag event.image.url(:original), width: '100%' %></td>
              <td><%= event.title %></td>
              <td class="text-center"><%= "#{format_datetime(event.started_at, 'past').delete('-').delete(' 전')} 후 게시 예정" %></td>
              <td class="text-center"><%= "#{((event.ended_at - event.started_at) / 60 / 60 / 24).to_i}일간 진행 예정" %><br><%= "#{format_datetime(event.started_at, :date)} ~ #{format_datetime(event.ended_at, :date)}" %></td>
              <td><%= link_to '조회', admin_event_path(event.id), class: 'btn btn-info btn-block' %></td>
              <td><%= link_to '수정', edit_admin_event_path(event.id), class: 'btn btn-warning btn-block' %></td>
              <td><%= link_to '삭제', admin_event_path(event.id), { class: 'btn btn-danger btn-block', method: :delete, data: { confirm: '정말로 삭제하시겠어요?', disable_with: '삭제중...' } } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<% unless @ongoings.blank? %>
  <div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">현재 진행중인 이벤트 목록</div>

    <!-- Table -->
    <div class="table-responsive">
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th style="width: 5%;">순번</th>
            <th style="width: 7.5%;">라벨</th>
            <th style="width: 20%;">이미지</th>
            <th style="width: 15%;">제목</th>
            <th style="width: 20%;">기간</th>
            <th style="width: 10%;">종료일</th>
            <th style="width: 7.5%;">조회</th>
            <th style="width: 7.5%;">수정</th>
            <th style="width: 7.5%;">삭제</th>
          </tr>
        </thead>
        <tbody>
          <% @ongoings.each_with_index do |event, index| %>
            <tr>
              <th><kbd><%= index + 1 %>번째</kbd></th>
              <td><%= event.label ? '<i class="fa fa-check text-success"></i>'.html_safe : '<i class="fa fa-remove text-danger"></i>'.html_safe %></td>
              <td><%= image_tag event.image.url(:original), width: '100%' %></td>
              <td><%= event.title %></td>
              <td class="text-center"><%= "#{((event.ended_at - event.started_at) / 60 / 60 / 24).to_i}일간 진행중" %><br><%= "#{format_datetime(event.started_at, :date)} ~ #{format_datetime(event.ended_at, :date)}" %></td>
              <td class="text-center"><%= "종료까지 #{format_datetime(event.ended_at, 'past').delete('-').delete(' 전')} 남음" %></td>
              <td><%= link_to '조회', admin_event_path(event.id), class: 'btn btn-info btn-block' %></td>
              <td><%= link_to '수정', edit_admin_event_path(event.id), class: 'btn btn-warning btn-block' %></td>
              <td><%= link_to '삭제', admin_event_path(event.id), { class: 'btn btn-danger btn-block', method: :delete, data: { confirm: '정말로 삭제하시겠어요?', disable_with: '삭제중...' } } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">경과한 이벤트 전체 목록</div>

  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th style="width: 5%;">ID</th>
          <th style="width: 7.5%;">라벨</th>
          <th style="width: 20%;">이미지</th>
          <th style="width: 15%;">제목</th>
          <th style="width: 20%;">기간</th>
          <th style="width: 10%;">종료일</th>
          <th style="width: 7.5%;">조회</th>
          <th style="width: 7.5%;">수정</th>
          <th style="width: 7.5%;">삭제</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <th><kbd><%= event.id %></kbd></th>
            <td><%= event.label ? '<i class="fa fa-check text-success"></i>'.html_safe : '<i class="fa fa-remove text-danger"></i>'.html_safe %></td>
            <td><%= image_tag event.image.url(:original), width: '100%' %></td>
            <td><%= event.title %></td>
            <td class="text-center"><%= "#{((event.ended_at - event.started_at) / 60 / 60 / 24).to_i}일간 진행됨" %><br><%= "#{format_datetime(event.started_at, :date)} ~ #{format_datetime(event.ended_at, :date)}" %></td>
            <td class="text-center"><%= "#{format_datetime(event.ended_at, 'past')}" %></td>
            <td><%= link_to '조회', admin_event_path(event.id), class: 'btn btn-info btn-block' %></td>
            <td><%= link_to '수정', edit_admin_event_path(event.id), class: 'btn btn-warning btn-block' %></td>
            <td><%= link_to '삭제', admin_event_path(event.id), { class: 'btn btn-danger btn-block', method: :delete, data: { confirm: '정말로 삭제하시겠어요?', disable_with: '삭제중...' } } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<!-- Table Pagination -->
<div class="text-center">
  <%= paginate @events %>
</div>

app/views/admin/events/show.html.erb
<div class="jumbotron clearfix">
  <h1><kbd><%= @event.id %>번</kbd> 이벤트</h1>
  <p>이벤트를 생성하거나 수정, 삭제할 수 있습니다</p>
  <%= link_to '목록으로',
              admin_events_path,
              { class: 'btn btn-default btn-lg' } %>
  <div class="pull-right">
    <%= link_to '수정하기',
                edit_admin_event_path(@event.id),
                { class: 'btn btn-warning btn-lg' } %>
    <%= link_to '삭제하기',
                admin_event_path(@event.id),
                { class: 'btn btn-danger btn-lg', method: :delete, data: { confirm: '정말로 삭제하시겠어요?', disable_with: '삭제중...' } } %>
  </div>
</div>

<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">이벤트 내용</div>
  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th style="width: 100px;">라벨 표시여부</th>
        <td><%= @event.label ? '<i class="fa fa-check text-success"></i>'.html_safe : '<i class="fa fa-remove text-danger"></i>'.html_safe %></td>
      </tr>
      <tr>
        <th>제목</th>
        <td><%= @event.title %></td>
      </tr>
      <tr>
        <th>설명</th>
        <td><%= tagging_keywords(@event.description) %></td>
      </tr>
      <tr>
        <th>시작일</th>
        <td><%= format_datetime(@event.started_at, :date) %></td>
      </tr>
      <tr>
        <th>종료일</th>
        <td><%= format_datetime(@event.ended_at, :date) %></td>
      </tr>
      <tr>
        <th>이미지</th>
        <td><%= image_tag @event.image.url(:original),
                          { width: '100%' } %></td>
      </tr>
      <tr>
        <th>질문</th>
        <td>
          <%= render '/admin/asks/thumbnail', ask: @event.ask %>
        </td>
      </tr>
    </table>
  </div>
</div>