config/routes.rb
Rails.application.routes.draw do

  resources :asks do
    member do
      get 'show_detail'
      post 'like'
    end
  end

  resources :ask_tmps, only: [:create]

  resources :votes, only: [:create, :destroy]

  resources :comments, only: [:index, :create, :update, :destroy] do
    member do
      post 'like'
    end
  end

  resources :preview_images, only: [:show, :create, :update]

  resources :deals, only: [] do
    collection do
      get 'get_naver_deals'
      post 'create_by_naver'
    end
  end

  resources :collections, only: [:index, :show]

  resources :videos, only: [:index, :show]

  resources :search, only: [:index] do
    collection do
      get 'keyword'
    end
  end

  resources :user_gcm_keys, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/facebook', to: 'users/facebook#auth'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'users/check_email', to: 'users/registrations#check_email'

    get 'users/forgot_password', to: 'users/passwords#new'
    get 'users/reset_password', to: 'users/passwords#edit'

    get 'users/alarm_check', to: 'users/sessions#alarm_check'
    get 'users/get_user_profile', to: 'users/sessions#get_user_profile'
    get 'users/get_user_alarms', to: 'users/sessions#get_user_alarms'
    get 'users/get_my_recent_ask', to: 'users/sessions#get_my_recent_ask'

    get 'users/', to: 'users/sessions#users'
    get 'users/history', to: 'users/sessions#history'
    get 'users/settings', to: 'users/sessions#settings'

    get 'users/settings/edit_profile', to: 'users/sessions#edit_profile'
    delete 'users/destroy_user_picture', to: 'users/sessions#destroy_user_picture'
    put 'users/change_nickname', to: 'users/sessions#change_nickname'

    get 'users/settings/edit_password', to: 'users/sessions#edit_password'
    put 'users/change_password', to: 'users/sessions#update_password'

    get 'users/settings/edit_push_alarm', to: 'users/sessions#edit_push_alarm'
    get 'users/settings/edit_email_alarm', to: 'users/sessions#edit_email_alarm'
    put 'users/toggle_alarm_option', to: 'users/sessions#toggle_alarm_option'
  end

  resources :log_errors, only: [:create]
  resources :log_inquiries, only: [:create]
  resources :log_reports, only: [:create]

  resources :shares, only: [:new, :create]
  resources :share_logs, only: [:create]

  resources :alarms, only: [:index]

  resources :etc, only: [] do
    collection do
      get 'access_term'
      get 'privacy_policy'
      get 'contact_us'
      get 'faq_help'
    end
  end

  get 'landing', to: 'home#landing'
  get 'open_app', to: 'home#open_app'

  namespace :admin do
    get '/', to: 'home#index'
    post '/sign_in', to: 'home#create'
    delete '/sign_out', to: 'home#destroy'
    resources :asks, only: [:index, :show, :update]
    resources :events
    resources :collections
    resources :collection_keywords, only: [:index, :create]
    resources :collection_to_collection_keywords, only: [:index]
    resources :collection_to_asks, only: [:create]
    resources :videos
    resources :grade_standards do
      put :force_update, on: :collection
      patch :cancel_modify, on: :member
    end
    resource :search_keywords, only: [:show, :create, :update, :destroy]
    resources :refer_links, except: [:delete]
    resources :pushes, only: [:index, :new, :create] do
      get :target, on: :collection
      get :test, on: :collection
    end
    resources :mails, except: [:edit, :update, :destroy] do
      get :target, on: :collection
      get :template, on: :collection
      post :test, on: :collection
    end
    resources :tables, only: [:index] do
      get ':table_name', to: 'tables#index', on: :collection
    end
    resources :analysis, only: [:index]
  end

  get 'templates/faq_help', to: 'templates#faq_help'
  get 'templates/access_term', to: 'templates#access_term'
  get 'templates/privacy_policy', to: 'templates#privacy_policy'

  root 'home#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  COLLECTION_PER = 3

  has_many :collection_to_asks
  has_many :asks, through: :collection_to_asks
  has_many :collection_to_collection_keywords
  has_many :collection_keywords, through: :collection_to_collection_keywords
  has_many :share_logs

  has_attached_file :image,
                    url: '/assets/collections/:id/:style/:basename.:extension',
                    path: ':rails_root/public/assets/collections/:id/:style/:basename.:extension',
                    default_url: '/images/custom/card_image_preview.png'
  validates_attachment_size :image, less_than: 20.megabytes
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/pjpeg', 'image/pjpeg', 'image/png', 'image/jpg', 'image/gif', 'application/octet-stream']

  validates :name, presence: true
  validates :description, presence: true
  validates :image, presence: true
  # validates :collection_keywords, presence: true
  # validates :asks, presence: true

  before_post_process :rename_file

  def rename_file
    return if image.blank?
    extension = image_file_name.split('.').last
    return unless %w[jpg jpeg gif png].include?(extension)
    self.image_file_name = "collection.#{extension}"
  end

  def fetch_related_collections
    keyword_ids = CollectionToCollectionKeyword.where(collection_id: id)
                                               .pluck(:collection_keyword_id)
    keyword_collections = CollectionToCollectionKeyword.where(collection_keyword_id: keyword_ids)
                                                       .where.not(collection_id: id)
    related_collections_ids = keyword_collections.group(:collection_id)
                                                 .order('collection_count DESC')
                                                 .select(:collection_id, 'count(collection_id) AS collection_count')
                                                 .map(&:collection_id)
    if related_collections_ids.empty?
      Collection.none
    else
      Collection.where(id: related_collections_ids)
                .where.not(published_at: nil)
                .order("FIELD(id,#{related_collections_ids.join(',')})")
    end
  end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < Admin::HomeController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /admin/collections
  def index
    @collections = Collection.where.not(published_at: nil)
                             .order(published_at: :desc)
                             .page(params[:page])
                             .per(10)
    @unpublished_collections = Collection.where(published_at: nil)
                                         .order(id: :desc)
  end

  # GET /admin/collections/:id
  def show
    @related_collections = @collection.fetch_related_collections
  end

  # GET /admin/collections/new
  def new
    @collection = Collection.new
  end

  # POST /admin/collections
  def create
    @collection = Collection.new(collection_params)
    if @collection.save
      generate_collection_asks(params[:collection][:asks])
      generate_collection_keywords(params[:collection][:collection_keywords])
      flash['success'] = "#{@collection.id}번 컬렉션을 성공적으로 생성하였습니다"
      redirect_to admin_collections_path
    else
      flash['error'] = '필수 입력값을 모두 입력해주세요'
      render :new
    end
  end

  # GET /admin/collections/:id/edit
  def edit
    return unless @collection.published_at
    flash['warning'] = '이미 발행한 컬렉션을 수정할 경우 다른 연관컬렉션에 영향을 미칠 수 있습니다'
  end

  # PATCH /admin/collections/:id
  def update
    if @collection.update(collection_params)
      generate_collection_asks(params[:collection][:asks])
      generate_collection_keywords(params[:collection][:collection_keywords])
      flash['success'] = "#{@collection.id}번 컬렉션을 성공적으로 수정하였습니다"
      redirect_to admin_collections_path
    else
      flash['error'] = '필수 입력값을 모두 입력해주세요'
      render :edit
    end
  end

  # DELETE /admin/collections/:id
  def destroy
    min_keywords = 3
    min_contents = 5

    if !@collection.published_at && @collection.collection_keywords.count < min_keywords
      flash['error'] = "컬렉션을 발행하려면 키워드를 최소 #{min_keywords}개 이상 포함해주세요"
      redirect_to :back and return
    elsif !@collection.published_at && @collection.asks.count < min_contents
      flash['error'] = "컬렉션을 발행하려면 컨텐츠를 최소 #{min_contents}개 이상 포함해주세요"
      redirect_to :back and return
    end

    @collection.published_at = @collection.published_at.nil? ? Time.now : nil
    if @collection.save
      unless @collection.published_at.nil?
        flash['success'] = "#{@collection.id}번 컬렉션을 성공적으로 발행하였습니다 <a href='#{collection_path(@collection.id)}' target='_blank' class='alert-link'>링크</a>"
      else
        flash['warning'] = "#{@collection.id}번 컬렉션을 발행 취소하였습니다"
      end
    else
      flash['error'] = "#{@collection.id}번 컬렉션 발행 전 필수 입력값을 모두 입력해주세요"
    end
    redirect_to :back
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name,
                                       :description,
                                       :image)
  end

  def generate_collection_asks(ask_ids)
    CollectionToAsk.destroy_all(collection_id: @collection.id)
    ask_ids.split(' ').each_with_index do |ask_id, index|
      CollectionToAsk.create(collection_id: @collection.id,
                             ask_id: ask_id,
                             seq: index)
    end
  end

  def generate_collection_keywords(collection_keyword_ids)
    CollectionToCollectionKeyword.destroy_all(collection_id: @collection.id)
    collection_keyword_ids.split(' ').each do |collection_keyword_id|
      CollectionToCollectionKeyword.create(collection_id: @collection.id,
                                           collection_keyword_id: collection_keyword_id)
      refer_count = CollectionToCollectionKeyword.where(collection_keyword_id: collection_keyword_id).count
      CollectionKeyword.find(collection_keyword_id).update(refer_count: refer_count)
    end
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show]

  # GET /collections
  # GET /collections.json
  def index
    respond_to do |format|
      format.html
      format.json do
        collections = Collection.where.not(published_at: nil)
                                .order(published_at: :desc)
                                .page(params[:page])
                                .per(Collection::COLLECTION_PER)
        is_more_load = collections.total_pages > params[:page].to_i
        render json: { collections: collections, is_more_load: is_more_load }
      end
    end
  end

  # GET /collections/:id
  # GET /collections/:id.json
  def show
    respond_to do |format|
      format.html
      format.json do
        collection = @collection

        if params[:related].nil?
          asks = collection.asks
                           .as_json(include: [{ user: { only: [:id, :string_id, :birthday, :gender, :avatar_file_name] } },
                                              { left_ask_deal: { include: [{ recent_comment: { include: [user: { only: [:id, :string_id] }] } } ] } },
                                              { right_ask_deal: { include: [{ recent_comment: { include: [user: { only: [:id, :string_id] }] } } ] } },
                                              :votes,
                                              { ask_likes: { include: { user: { only: [:id, :string_id] } } } },
                                              :ask_complete,
                                              :event])
        else
          related_collections = collection.fetch_related_collections.limit(5)

          if related_collections.blank?
            recent_asks = Ask.order(id: :desc).limit(Ask::ASK_PER)
            if current_user
              my_votes = Vote.where(user_id: current_user.id).map(&:ask_id)
              recent_asks = recent_asks.where.not(user_id: current_user.id)
              recent_asks = recent_asks.where.not(id: my_votes) unless my_votes.empty?
            end
          end
        end

        render json: {
          collection: collection,
          asks: asks,
          related_collections: related_collections,
          recent_asks: recent_asks
        }
      end
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end
end

app/views/admin/collections/_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered table-striped table-hover">
    <thead>
      <tr>
        <th style="width: 5%;">ID</th>
        <th style="width: 5%;">이미지</th>
        <th style="width: 10%;">제목</th>
        <th style="width: 10%;">설명</th>
        <th style="width: 10%;">게시일</th>
        <th style="width: 10%;">컨텐츠</th>
        <th style="width: 10%;">키워드</th>
        <th style="width: 10%;">연관컬렉션</th>
        <th style="width: 10%;">조회</th>
        <th style="width: 10%;">수정</th>
        <th style="width: 10%;">발행</th>
      </tr>
    </thead>
    <tbody>
      <% collections.each do |collection| %>
        <tr>
          <th><kbd><%= collection.id %></kbd></th>
          <td><%= image_tag collection.image.url(:original), width: '100%' %></td>
          <td><%= collection.name %></td>
          <td><%= tagging_keywords(collection.description) %></td>
          <td class="text-center"><%= collection.published_at ? format_datetime(collection.published_at, 'past') : '미게시' %></td>
          <td><%= link_to "#{collection.asks.count}개", admin_collection_path(collection.id), class: 'btn btn-default btn-block' %></td>
          <td><%= link_to "#{collection.collection_keywords.count}개", admin_collection_path(collection.id), class: 'btn btn-default btn-block' %></td>
          <td><%= link_to "#{collection.fetch_related_collections.count}개", admin_collection_path(collection.id), class: 'btn btn-default btn-block' %></td>
          <td><%= link_to '조회', admin_collection_path(collection.id), class: 'btn btn-info btn-block' %></td>
          <td><%= link_to '수정', edit_admin_collection_path(collection.id), class: 'btn btn-warning btn-block' %></td>
          <td>
            <% if collection.published_at %>
              <%= link_to '발행취소', admin_collection_path(collection.id), { class: 'btn btn-danger btn-block', method: :delete, data: { confirm: '정말로 발행을 취소하시겠어요?', disable_with: '취소중...' } } %>
            <% else %>
              <%= link_to '발행하기', admin_collection_path(collection.id), { class: 'btn btn-success btn-block', method: :delete, data: { confirm: '정말로 발행하시겠어요?', disable_with: '발행중...' } } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/collections/index.html.erb
<div class="jumbotron clearfix">
  <h1>컬렉션 목록</h1>
  <p>컬렉션을 생성하거나 수정, 발행할 수 있습니다</p>
  <%= link_to '새로운 컬렉션 생성하기',
              new_admin_collection_path,
              { class: 'btn btn-success btn-lg pull-right' } %>
</div>

<% unless @unpublished_collections.blank? %>
  <div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">미발행된 컬렉션 목록</div>
    <!-- Table -->
    <%= render 'table', collections: @unpublished_collections %>
  </div>
<% end %>

<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading">컬렉션 전체 목록</div>
  <!-- Table -->
  <%= render 'table', collections: @collections %>
</div>
<!-- Table Pagination -->
<div class="text-center">
  <%= paginate @collections %>
</div>

app/views/admin/collections/show.html.erb
<div class="jumbotron clearfix">
  <h1><kbd><%= @collection.id %>번</kbd> 컬렉션</h1>
  <p>컬렉션을 생성하거나 수정, 발행할 수 있습니다</p>
  <%= link_to '목록으로',
              admin_collections_path,
              { class: 'btn btn-default btn-lg' } %>
  <div class="pull-right">
    <%= link_to '링크열기',
                collection_path(@collection.id),
                { class: 'btn btn-default btn-lg', target: '_blank' } %>
    <%= link_to '수정하기',
                edit_admin_collection_path(@collection.id),
                { class: 'btn btn-warning btn-lg' } %>
    <% unless @collection.published_at.nil? %>
      <%= link_to '발행취소', admin_collection_path(@collection.id), { class: 'btn btn-danger btn-lg', method: :delete, data: { confirm: '정말로 발행을 취소하시겠어요?', disable_with: '취소중...' } } %>
    <% else %>
      <%= link_to '발행하기', admin_collection_path(@collection.id), { class: 'btn btn-success btn-lg', method: :delete, data: { confirm: '정말로 발행하시겠어요?', disable_with: '발행중...' } } %>
    <% end %>
  </div>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading" role="tab">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        컬렉션 내용
      </a>
    </div>
    <!-- Table -->
    <div id="collapseOne" class="panel panel-collapse collapse in" role="tabpanel">
      <div class="table-responsive">
        <table class="table table-bordered">
          <tr>
            <th style="width: 100px;">제목</th>
            <td><%= @collection.name %></td>
          </tr>
          <tr>
            <th>설명</th>
            <td><%= tagging_keywords(@collection.description) %></td>
          </tr>
          <tr>
            <th>키워드</th>
            <td>
              <% if @collection.collection_keywords.blank? %>
                키워드를 추가해주세요
              <% else %>
                <% @collection.collection_keywords.each do |keyword| %>
                  <span class="label label-danger"><%= keyword.keyword %></span>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>게시일</th>
            <td><%= @collection.published_at ? format_datetime(@collection.published_at, :date) : '아직 게시하지 않았습니다' %></td>
          </tr>
          <tr>
            <th>이미지</th>
            <td><%= image_tag @collection.image.url(:original), width: '100%' %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading" role="tab">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        연관 컬렉션 <span class="badge pull-right"><%= "#{@related_collections.length}개" %></span>
      </a>
    </div>

    <!-- Table -->
    <div id="collapseTwo" class="panel panel-collapse collapse" role="tabpanel">
      <div class="table-responsive">
        <table class="table table-bordered">
          <% if @related_collections.blank? %>
            <tr>
              <th style="width: 100px;">연관컬렉션</th>
              <td>키워드를 더 추가해주세요</td>
            </tr>
          <% else %>
            <% @related_collections.each_with_index do |id, index| %>
              <tr>
                <th style="width: 100px;">연관 컬렉션 <%= index + 1 %></th>
                <td>
                  <% collection = Collection.find(id) %>
                  <dl>
                    <dt><%= collection.name %></dt>
                    <dd><%= collection.description %></dd>
                  </dl>
                  <%= image_tag collection.image.url(:normal),
                                { width: '100%', class: 'img-thumbnail' } %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <div class="panel panel-info">
    <!-- Default panel contents -->
    <div class="panel-heading" role="tab">
      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
        포함된 컨텐츠 <span class="badge pull-right"><%= "#{@collection.asks.length}개" %></span>
      </a>
    </div>

    <!-- Table -->
    <div id="collapseThree" class="panel panel-collapse collapse" role="tabpanel">
      <div class="table-responsive">
        <table class="table table-bordered">
          <% if @collection.asks.blank? %>
            <tr>
              <th style="width: 100px;">컨텐츠</th>
              <td>컨텐츠를 추가해주세요</td>
            </tr>
          <% else %>
            <% @collection.asks.each_with_index do |ask, index| %>
              <tr>
                <th style="width: 100px;">컨텐츠 <%= index + 1 %></th>
                <td>
                  <dl>
                    <dt><%= ask.user.string_id %>님의 질문</dt>
                    <dd><%= tagging_keywords(ask.message) %></dd>
                  </dl>
                  <%= image_tag ask.left_ask_deal.image.url(:normal),
                                { width: '50%', class: 'img-thumbnail pull-left' } %>
                  <%= image_tag ask.right_ask_deal.image.url(:normal),
                                { width: '50%', class: 'img-thumbnail pull-left' } %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>