config/routes.rb
Rails.application.routes.draw do

  resources :asks do
    member do
      get 'show_detail'
      post 'like'
    end
  end

  resources :ask_tmps, only: [:create]

  resources :votes, only: [:create, :destroy]

  resources :comments, only: [:index, :create, :update, :destroy] do
    member do
      post 'like'
    end
  end

  resources :preview_images, only: [:show, :create, :update]

  resources :deals, only: [] do
    collection do
      get 'get_naver_deals'
      post 'create_by_naver'
    end
  end

  resources :collections, only: [:index, :show]

  resources :videos, only: [:index, :show]

  resources :search, only: [:index] do
    collection do
      get 'keyword'
    end
  end

  resources :user_gcm_keys, only: [:create]

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/facebook', to: 'users/facebook#auth'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'users/check_email', to: 'users/registrations#check_email'

    get 'users/forgot_password', to: 'users/passwords#new'
    get 'users/reset_password', to: 'users/passwords#edit'

    get 'users/alarm_check', to: 'users/sessions#alarm_check'
    get 'users/get_user_profile', to: 'users/sessions#get_user_profile'
    get 'users/get_user_alarms', to: 'users/sessions#get_user_alarms'
    get 'users/get_my_recent_ask', to: 'users/sessions#get_my_recent_ask'

    get 'users/', to: 'users/sessions#users'
    get 'users/history', to: 'users/sessions#history'
    get 'users/settings', to: 'users/sessions#settings'

    get 'users/settings/edit_profile', to: 'users/sessions#edit_profile'
    delete 'users/destroy_user_picture', to: 'users/sessions#destroy_user_picture'
    put 'users/change_nickname', to: 'users/sessions#change_nickname'

    get 'users/settings/edit_password', to: 'users/sessions#edit_password'
    put 'users/change_password', to: 'users/sessions#update_password'

    get 'users/settings/edit_push_alarm', to: 'users/sessions#edit_push_alarm'
    get 'users/settings/edit_email_alarm', to: 'users/sessions#edit_email_alarm'
    put 'users/toggle_alarm_option', to: 'users/sessions#toggle_alarm_option'
  end

  resources :log_errors, only: [:create]
  resources :log_inquiries, only: [:create]
  resources :log_reports, only: [:create]

  resources :shares, only: [:new, :create]
  resources :share_logs, only: [:create]

  resources :alarms, only: [:index]

  resources :etc, only: [] do
    collection do
      get 'access_term'
      get 'privacy_policy'
      get 'contact_us'
      get 'faq_help'
    end
  end

  get 'landing', to: 'home#landing'
  get 'open_app', to: 'home#open_app'

  namespace :admin do
    get '/', to: 'home#index'
    post '/sign_in', to: 'home#create'
    delete '/sign_out', to: 'home#destroy'
    resources :asks, only: [:index, :show, :update]
    resources :events
    resources :collections
    resources :collection_keywords, only: [:index, :create]
    resources :collection_to_collection_keywords, only: [:index]
    resources :collection_to_asks, only: [:create]
    resources :videos
    resources :grade_standards do
      put :force_update, on: :collection
      patch :cancel_modify, on: :member
    end
    resource :search_keywords, only: [:show, :create, :update, :destroy]
    resources :refer_links, except: [:delete]
    resources :pushes, only: [:index, :new, :create] do
      get :target, on: :collection
      get :test, on: :collection
    end
    resources :mails, except: [:edit, :update, :destroy] do
      get :target, on: :collection
      get :template, on: :collection
      post :test, on: :collection
    end
    resources :tables, only: [:index] do
      get ':table_name', to: 'tables#index', on: :collection
    end
    resources :analysis, only: [:index]
  end

  get 'templates/faq_help', to: 'templates#faq_help'
  get 'templates/access_term', to: 'templates#access_term'
  get 'templates/privacy_policy', to: 'templates#privacy_policy'

  root 'home#index'

end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < Admin::HomeController
  # GET /admin/notices
  def index
    @notices = LogPushAdmin.page(params[:page]).per(10).order(id: :desc)
  end

  # GET /admin/notices/new
  def new
  end

  # GET /admin/notices/target
  def target
  end

  # GET /admin/notices/test
  def test
    return if params[:msg].blank? || params[:link].blank?
    params[:js] = '' if params[:js].nil? || params[:js] == 'false'
    payload = { msg: "#{params[:msg]}\n[테스트 푸쉬 by #{current_user.string_id}]",
                type: 'true',
                count: nil,
                id: 1,
                link: params[:link],
                js: params[:js] }
    registration_ids_ios = UserGcmKey.where(user_id: 1).where('device_id LIKE ?', 'ios%').pluck(:gcm_key)
    registration_ids_aos = UserGcmKey.where(user_id: 1).where('device_id LIKE ?', 'android%').pluck(:gcm_key)

    response_ios = push_send_IOS(registration_ids_ios, payload) unless registration_ids_ios.blank?
    response_aos = push_send_AOS(registration_ids_aos, payload) unless registration_ids_aos.blank?

    count = 0
    count += JSON.parse(response_ios[:body])['success'].to_i unless response_ios.nil?
    count += JSON.parse(response_aos[:body])['success'].to_i unless response_aos.nil?
    @string = "#{count}대의 기기에 테스트 알림을 전송하였습니다"
  end

  # POST /admin/notices
  def create
    if params[:type].blank? || params[:target].blank? || params[:msg].blank? || params[:link].blank?
      flash['error'] = '필수 입력값을 모두 입력해주세요'
      redirect_to new_admin_notice_path and return
    end

    push_type = params[:type]
    params[:js] = '' if params[:js].nil? || params[:js] == 'false'
    payload = { msg: params[:msg],
                type: 'true',
                count: nil,
                id: 1,
                link: params[:link],
                js: params[:js] }

    if params[:target] == 'all'
      if Rails.env == 'development'
        admin_user_ids = User.where(user_role: 'admin').pluck(:id)
        registration_ids_ios = UserGcmKey.where(user_id: admin_user_ids).where('device_id LIKE ?', 'ios%').pluck(:gcm_key)
        registration_ids_aos = UserGcmKey.where(user_id: admin_user_ids).where('device_id LIKE ?', 'android%').pluck(:gcm_key)
      else
        registration_ids_ios = UserGcmKey.where('device_id LIKE ?', 'ios%').pluck(:gcm_key)
        registration_ids_aos = UserGcmKey.where('device_id LIKE ?', 'android%').pluck(:gcm_key)
      end
    elsif params[:target] == 'filter'
      target_users =
        if Rails.env == 'development'
          User.where(user_role: 'admin')
        else
          User.all
        end

      unless params[:filter_gender].nil?
        if params[:filter_gender].length == 1 && params[:filter_gender][0] == 'male'
          target_users = target_users.where(gender: true)
        elsif params[:filter_gender].length == 1 && params[:filter_gender][0] == 'female'
          target_users = target_users.where(gender: false)
        end
      end

      unless params[:filter_age].nil?
        if params[:filter_age].length > 0 && params[:filter_age].length < 7
          age_filter = []
          age_20 = Date.new(Time.now.year - 18, 1, 1)
          age_20_1_end = Date.new(Time.now.year - 22, 1, 1)
          age_20_2_end = Date.new(Time.now.year - 25, 1, 1)
          age_30 = Date.new(Time.now.year - 28, 1, 1)
          age_30_1_end = Date.new(Time.now.year - 32, 1, 1)
          age_30_2_end = Date.new(Time.now.year - 35, 1, 1)
          age_30_3_end = Date.new(Time.now.year - 38, 1, 1)
          params[:filter_age].each do |age|
            age_filter << "users.birthday < '#{age_20}' AND users.birthday > '#{age_20_1_end}'" if age == 'early_20'
            age_filter << "users.birthday < '#{age_20_1_end}' AND users.birthday > '#{age_20_2_end}'" if age == 'middle_20'
            age_filter << "users.birthday < '#{age_20_2_end}' AND users.birthday > '#{age_30}'" if age == 'latter_20'
            age_filter << "users.birthday < '#{age_30}' AND users.birthday > '#{age_30_1_end}'" if age == 'early_30'
            age_filter << "users.birthday < '#{age_30_1_end}' AND users.birthday > '#{age_30_2_end}'" if age == 'middle_30'
            age_filter << "users.birthday < '#{age_30_2_end}' AND users.birthday > '#{age_30_3_end}'" if age == 'latter_30'
            age_filter << "users.birthday IS NULL OR (users.birthday > '#{age_20}' OR users.birthday < '#{age_30_3_end}')" if age == 'etc'
          end
          target_users = target_users.where(age_filter.join(' OR '))
        end
      end

      ios_checked = true
      aos_checked = true
      if !params[:filter_device].nil? && params[:filter_device].length == 1
        ios_checked = false
        aos_checked = false
        params[:filter_device].each do |device|
          ios_checked = true if device == 'ios'
          aos_checked = true if device == 'aos'
        end
      end

      target_user_ids = target_users.pluck(:id)
      registration_ids_ios = UserGcmKey.where(user_id: target_user_ids).where('device_id LIKE ?', 'ios%').pluck(:gcm_key) if ios_checked
      registration_ids_aos = UserGcmKey.where(user_id: target_user_ids).where('device_id LIKE ?', 'android%').pluck(:gcm_key) if aos_checked
    elsif params[:target] == 'user'
      target_user_ids = params[:target_user_id]
      registration_ids_ios = UserGcmKey.where(user_id: target_user_ids).where('device_id LIKE ?', 'ios%').pluck(:gcm_key)
      registration_ids_aos = UserGcmKey.where(user_id: target_user_ids).where('device_id LIKE ?', 'android%').pluck(:gcm_key)
    end

    response_ios = push_send_IOS(registration_ids_ios, payload) unless registration_ids_ios.blank?
    response_aos = push_send_AOS(registration_ids_aos, payload) unless registration_ids_aos.blank?

    ios_count = 0
    aos_count = 0
    success_count = 0
    failure_count = 0

    unless response_ios.nil?
      body_ios = JSON.parse(response_ios[:body])
      success_count += body_ios['success'].to_i
      failure_count += body_ios['failure'].to_i
      ios_count = registration_ids_ios.length.to_i
    end

    unless response_aos.nil?
      body_aos = JSON.parse(response_aos[:body])
      success_count += body_aos['success'].to_i
      failure_count += body_aos['failure'].to_i
      aos_count = registration_ids_aos.length.to_i
    end

    total_count = ios_count + aos_count

    LogPushAdmin.create(
      push_type: push_type,
      total_count: total_count,
      ios_count: ios_count,
      aos_count: aos_count,
      success_count: success_count,
      failure_count: failure_count,
      message: payload[:msg]
    )

    flash['success'] = "총 #{success_count}개의 푸시알림을 성공적으로 전송하였습니다"
    redirect_to admin_notices_path
  end
end

app/views/admin/notices/index.html.erb
<div class="jumbotron clearfix">
  <h1>푸쉬알림 목록</h1>
  <p>푸쉬알림 전송 목록입니다</p>
  <%= link_to '새로운 푸쉬알림 전송하기',
              new_admin_notice_path,
              { class: 'btn btn-success btn-lg pull-right' } %>
</div>
<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">푸쉬알림 히스토리</div>

  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th style="width: 50px;">ID</th>
          <th style="width: 100px;">구분</th>
          <th>내용</th>
          <th style="width: 80px;">전송 요청</th>
          <th style="width: 80px;">전송 성공</th>
          <th style="width: 80px;">전송 실패</th>
          <th style="width: 120px;">전송일</th>
        </tr>
      </thead>
      <tbody>
        <% @notices.each do |notice| %>
          <tr>
            <td><kbd><%= notice.id %></kbd></td>
            <td><%= notice.push_type %></td>
            <td><%= simple_format(notice.message, {}, wrapper_tag: 'div') %></td>
            <td><%= notice.total_count %>개</td>
            <td><%= notice.success_count %>개</td>
            <td><%= notice.failure_count %>개</td>
            <td><%= format_datetime(notice.created_at, :datetime) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- Table Pagination -->
  <div class="panel-footer text-center">
    <%= paginate @notices %>
  </div>
</div>

app/views/admin/notices/new.html.erb
<%= form_tag({ controller: :notices, action: :create },
            oninput: 'form_check($(this));', onchange: 'form_check($(this));') do %>
  <div class="jumbotron clearfix">
    <h1>푸쉬알림 전송하기</h1>
    <p>푸쉬알림을 전송할 수 있습니다</p>
    <%= link_to '목록으로',
                admin_notices_path,
                { class: 'btn btn-default btn-lg' } %>
    <div class="pull-right">
      <%= link_to '푸시알림 테스트',
                  test_admin_notices_path,
                  remote: true,
                  id: 'push_test_btn',
                  class: 'btn btn-success btn-lg',
                  onclick: 'push_test_send();',
                  data: { disable_with: '<i class="fa fa-spinner fa-spin"></i>' } %>
      <%= submit_tag '푸시알림 전송하기',
                     id: 'push_submit_btn',
                     class: 'btn btn-danger btn-lg',
                     disabled: true,
                     onclick: 'window.onbeforeunload = null;',
                     data: { confirm: '정말로 전송하시겠어요?', disable_with: '전송중...' } %>
    </div>
  </div>
  <div class="panel panel-danger">
    <div class="panel-heading">푸쉬알림 전송하기</div>
    <div class="panel-body">
      <div class="form-inputs">
        <div class="form-group">
          <label for="type">1. 푸시 종류 선택</label>
          <%= select_tag :type,
                         '
                          <option value disabled selected>푸쉬 종류를 선택해주세요</option>
                          <optgroup label="컨텐츠 생성">
                            <option value="collection">컬렉션 발행</option>
                            <option value="video">비교영상 발행</option>
                            <option value="event">이벤트 생성</option>
                          </optgroup>
                          <optgroup label="일반">
                            <option value="notice">공지사항</option>
                          </optgroup>
                         '.html_safe,
                         {
                           class: 'form-control required_form',
                           onchange: 'push_type_changed($(this));'
                         } %>
        </div>
        <div class="form-group">
          <label for="target">2. 대상 선택</label>
          <div class="form-group">
            <%= select_tag :target,
                           '
                            <option value disabled selected>대상을 선택해주세요</option>
                            <option value="all">전체 유저</option>
                            <option value="filter">필터 적용</option>
                            <option value="user">특정 유저</option>
                           '.html_safe,
                           {
                             class: 'form-control required_form',
                             onchange: 'push_target_changed($(this));'
                           } %>
          </div>
          <div id="push_target_preview" class="well hidden"></div>
        </div>
        <div class="form-group">
          <label for="msg">3. 푸쉬알림 내용 입력</label>
          <%= text_area_tag :msg,
                            '',
                            {
                              rows: 3,
                              class: 'form-control required_form',
                              placeholder: '전송될 푸쉬알림의 내용을 입력해주세요'
                            } %>
        </div>
        <div class="form-group">
          <label for="link">4. 푸쉬알림 연결 링크 입력</label>
          <p class="help-block">연결할 링크를 입력한 뒤 미리보기 버튼을 누르세요</p>
          <div class="input-group">
            <%= text_field_tag :link,
                               "#{CONFIG['host']}",
                               {
                                 class: 'form-control required_form',
                                 placeholder: '연결할 링크를 입력해주세요',
                                 onchange: "$('#preview_link_btn').click();"
                               } %>
             <span class="input-group-btn">
               <button class="btn btn-default" type="button" onclick="preview_link_reset('VASKIT', $('#link'), $('#js'), $('#push_link_preview'), $('#preview_completed'));"><i class="fa fa-home"></i> 초기화</button>
               <button id="preview_link_btn" class="btn btn-success" type="button" onclick="preview_link('VASKIT', $('#link'), $('#js'), $('#push_link_preview'), $('#preview_completed'));"><i class="fa fa-search"></i> 미리보기</button>
             </span>
          </div>
          <%= check_box_tag 'preview_completed', '', false, class: 'hidden required_form' %>
        </div>
        <div class="form-group">
          <%= text_field_tag :js,
                             '',
                             {
                               class: 'form-control hidden',
                               readonly: true,
                               placeholder: ''
                             } %>
        </div>
        <div id="push_link_preview" class="well hidden">
          <div class="embed-responsive embed-responsive-4by3">
            <iframe class="embed-responsive-item" src=""></iframe>
            <div class="iframe_cover" onclick="window.open($(this).prev('iframe').attr('src'));"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
  function push_test_send() {
    var msg = encodeURIComponent($('#msg').val());
    var link = encodeURIComponent($('#link').val());
    var js = encodeURIComponent($('#js').val());
    $('#push_test_btn').attr('href', '<%= test_admin_notices_path %>?msg=' + msg + '&link=' + link + '&js=' + js);
  }

  function push_type_changed() {
    var type_input = $('#type');
    var link_input = $('#link');
    var type = type_input.val();
    if (type == 'collection') {
      link_input.val('<%= "#{collections_url}/#{Collection.last.id}" %>');
    } else if (type == 'video') {
      link_input.val('<%= "#{videos_url}/" %>');
    } else if (type == 'event') {
      link_input.val('<%= "#{asks_url}/#{Event.last.ask_id}" %>');
    } else if (type == 'notice') {
      link_input.val('<%= "#{root_url}" %>');
    }
  }

  function push_target_changed() {
    $.ajax({
      url: '<%= target_admin_notices_path %>',
      type: 'GET',
      data: { target: $('#target').val() },
      beforeSend: function() {
        $('#push_target_preview').removeClass('hidden').html('갱신중...');
      }
    });
  }
</script>